#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd -P)

VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
curl -sSL -o "${SCRIPT_DIR}/argocd" "https://github.com/argoproj/argo-cd/releases/download/${VERSION}/argocd-linux-amd64"
chmod +x "${SCRIPT_DIR}/argocd"
