#!/bin/bash

MIN_VERSION=${1:-"v11.99.99"}
VERSION=$(node --version)
cat > ./tmp-node-version <<-END
$VERSION
$MIN_VERSION
END

LATEST_VERSION=$(cat ./tmp-node-version | sort --version-sort | tail -1)

rm ./tmp-node-version

if [[ "${LATEST_VERSION}" == "${MIN_VERSION}" ]]; then
  exit 1
else
  exit 0
fi
