#!/bin/bash

mkdir -p ~/bin
cp icc ~/bin

if [[ "${SHELL}" =~ zsh ]]; then
  if ! grep -qE 'export PATH=.*${HOME}/bin' ~/.zshrc; then
    echo 'export PATH="${HOME}/bin:${PATH}"' >> ~/.zshrc
  fi
else
  if ! grep -qE 'export PATH=.*${HOME}/bin' ~/.bashrc; then
    echo 'export PATH="${HOME}/bin:${PATH}"' >> ~/.bashrc
  fi
fi
