#!/bin/bash

VERSION=$(curl --silent "https://api.github.com/repos/tektoncd/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
SEM_VER=$(echo "${VERSION}" | sed "s/v//g")

curl -LO "https://github.com/tektoncd/cli/releases/download/${VERSION}/tkn_${SEM_VER}_Linux_arm64.tar.gz"
sudo tar xvzf "tkn_${SEM_VER}_Linux_arm64.tar.gz" -C "${PWD}" tkn
