#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)

if command -v node > /dev/null && "${SCRIPT_DIR}/check-node-version"; then
  NPM_PREFIX=$(npm config get prefix)

  if [[ ! -w "${NPM_PREFIX}" ]]; then
    echo " + Setting new NPM prefix directory"
    rm -rf ~/.npm
    mkdir ~/.npm
    npm config set prefix ~/.npm

    if [[ "${SHELL}" =~ zsh ]]; then
      echo 'export PATH=~/.npm/bin:$PATH' >> ~/.zshrc
      . ~/.zshrc
    else
      echo 'export PATH=~/.npm/bin:$PATH' >> ~/.bashrc
      . ~/.bashrc
    fi
  fi
else
  NVM_INSTALL="true"

  echo " + Installing LTS version of Node with nvm"
  curl -so- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash > /dev/null

  if [[ "${SHELL}" =~ zsh ]]; then
    . ~/.zshrc
  else
    . ~/.bashrc
  fi

  nvm install --lts
fi

echo " + Installing Cloud-Native Toolkit cli"
npm i -g --silent @ibmgaragecloud/cloud-native-toolkit-cli

if [[ -n "${NVM_INSTALL}" ]]; then
  echo ""
  echo "A new version of Node has been installed with NVM"
  echo -e "  Run \e[97mnvm use default\e[0m"
fi
