#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

mkdir -p ~/bin

if [[ "${machine}" == "Mac" ]]; then
    curl -Lo ~/bin/openshift-client.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-mac.tar.gz
else
    curl -Lo ~/bin/openshift-client.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
fi

cd ~/bin
tar xzf openshift-client.tar.gz
rm openshift-client.tar.gz

if [[ "${SHELL}" =~ zsh ]]; then
  if ! grep -qE "export PATH=.*~/bin" ~/.zshrc; then
    echo 'export PATH="~/bin:${PATH}"' >> ~/.zshrc
  fi
else
  if ! grep -qE "export PATH=.*~/bin" ~/.bashrc; then
    echo 'export PATH="~/bin:${PATH}"' >> ~/.bashrc
  fi
fi
