#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)

if command -v node > /dev/null && "${SCRIPT_DIR}/check-node-version"; then
  NPM_PREFIX=$(npm config get prefix)

  if [[ ! -w "${NPM_PREFIX}" ]]; then
    echo "  + Setting new NPM prefix directory"
    rm -rf ~/.npm
    mkdir ~/.npm
    npm config set prefix ~/.npm

    if [[ "${SHELL}" =~ zsh ]]; then
      if ! grep -qE "export PATH=.*~/.npm/bin" ~/.zshrc; then
        echo 'export PATH="~/.npm/bin:${PATH}"' >> ~/.zshrc
      fi
      . ~/.zshrc
    else
      if ! grep -qE "export PATH=.*~/.npm/bin" ~/.bashrc; then
        echo 'export PATH="~/.npm/bin:${PATH}"' >> ~/.bashrc
      fi
      . ~/.bashrc
    fi
  fi
else
  NVM_INSTALL="true"

  echo "  + Installing LTS version of Node with nvm"
  curl -so- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash > /dev/null

  if [[ "${SHELL}" =~ zsh ]]; then
    . ~/.zshrc
  else
    . ~/.bashrc
  fi

  nvm install --lts
fi

echo "  + Installing igc cli"
npm i -g --silent @ibmgaragecloud/cloud-native-toolkit-cli 1> /dev/null

if [[ -n "${NVM_INSTALL}" ]]; then
  echo ""
  echo "A new version of Node has been installed with NVM"
  echo -e "  Run \e[97mnvm use default\e[0m"
fi
