#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd -P)

curl -sLO https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh && \
  chmod +x kube-ps1.sh

if ! grep -q "# KUBE_PS1 start" ~/.zshrc; then
  cat "${SCRIPT_DIR}/config/zsh-kube" >> ~/.zshrc
fi
