#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

mkdir -p ~/bin

if [[ "${machine}" == "Mac" ]]; then
    curl -Lo ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
else
    curl -Lo ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
fi

if [[ "${SHELL}" =~ zsh ]]; then
  if ! grep -qE 'export PATH=.*${HOME}/bin' ~/.zshrc; then
    echo 'export PATH="${HOME}/bin:${PATH}"' >> ~/.zshrc
  fi
else
  if ! grep -qE 'export PATH=.*${HOME}/bin' ~/.bashrc; then
    echo 'export PATH="${HOME}/bin:${PATH}"' >> ~/.bashrc
  fi
fi
