name: Publish assets

on:
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    #    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Asset
        run: |
          mkdir dist
          cd assets
          tar czf ../dist/assets.tar.gz .

      - name: Upload Tar
        id: upload-tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/assets.tar.gz
          asset_name: assets.tar.gz
          asset_content_type: application/gzip

      - name: Upload Install Script
        id: upload-install-script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/install.sh
          asset_name: install.sh
          asset_content_type: text/plain
